### ISSUE TITLE
Ray query support

### ISSUE THREAD

**Issue by JonSargent** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#11]
Are low-level ray queries (e.g. arbitrary origin rays, intersection data, etc.) accessible from the ProRender SDK? Or only from RadeonRays? I'd like to be able to access these features without losing the convenience of ProRender's material support.

Also, out of curiosity, is there another developer forum elsewhere? Light traffic here, so just wondering if I'm in the right place. :)

**Comment by bsavery** [comment]
Hi Jon.  No, that info isn't available in RPR, but is in radeon rays of course.  There are of course maybe a few options here.  Can you give some more details of what you're trying to achieve?  Is this for a game?  Are you writing a renderer?  What do you want to do with this data?

**Comment by JonSargent** [comment]
Thanks for the quick response @bsavery. Not precisely either. We use ray tracers to make predictions about the behavior of light in buildings (and its effect on human occupants). Sometimes renderings are involved, other times not. Access to [flexible I/O parameters](https://floyd.lbl.gov/radiance/rtrace.1.html) is critical for the analysis, but so is physically-based material support. Rewriting the latter from scratch sounds less than ideal. Are the APIs open / extensible in any way?
