### ISSUE TITLE
libRadeonProRender64 is not getting loaded

### ISSUE THREAD

**Issue by ikamthania** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#14]
Tried the sdk tutorial building instructions on Ubuntu 20.04 and macOS. Both of them failed

On Ubuntu 
```
./21_material_layered64: error while loading shared libraries: libRadeonProRender64.so: cannot open shared object file: No such file or directory
```
On macOS
```
dyld: Library not loaded: @rpath/libRadeonProRender64.dylib
  Referenced from: /Users/shubham/git/RadeonProRenderSDK/tutorials/Bin/./22_material_uber64
  Reason: image not found
```
Also on Ubuntu glew.h is not included resulting in this error
```
In file included from ../32_gl_interop/ShaderManager.cpp:1:
../32_gl_interop/ShaderManager.h:30:10: fatal error: GL/glew.h: No such file or directory
   30 | #include <GL/glew.h>

```

**Comment by bsavery** [comment]
Your issue here on Mac sounds different than the ubuntu one.  

1.  macOS.  Set DYLD_LIBRARY_PATH env variable to where the libRadeonProRender64.dylib lives
2.  Ubuntu.  Set LD_LIBRARY_PATH the same way.  Your glew.h probably sounds like you need to install GLEW
