### ISSUE TITLE
Node Input not getting removed in Northstar64 but Tahoe64 its fine

### ISSUE THREAD

**Issue by Mentalarray** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#16]
This simple example works in Tahoe64 perfectly but in Northstar64 the removing line does nothing and throws no error
i have not checked any other nodes as i have only just started adding them, but in this case it happends with the "Blend" node. 
` //add MICROFACET
            Rpr.Check((int)Rpr.MaterialSystemCreateNode(g_matsys, Rpr.MaterialNodeType.MICROFACET, out micro_mat));
            //set rough
            Rpr.Check((int)Rpr.MaterialNodeSetInputFByKey(micro_mat, Rpr.MaterialInput.ROUGHNESS, 0.5f,0.5f,0.5f,0.5f));
            //add Blend
            Rpr.Check((int)Rpr.MaterialSystemCreateNode(g_matsys, Rpr.MaterialNodeType.BLEND, out blend_mat));
            //set weight to 0
            Rpr.Check((int)Rpr.MaterialNodeSetInputFByKey(blend_mat, Rpr.MaterialInput.WEIGHT, 0, 0, 0, 0));
            //set blend input COLOR0 to micro_mat
            Rpr.Check((int)Rpr.MaterialNodeSetInputNByKey(blend_mat, Rpr.MaterialInput.COLOR0, micro_mat));

            //removing micro_mat from blend input COLOR0
            //this line does not work to remove material with Northstar64 but Tahoe64 it works fine
            Rpr.Check((int)Rpr.MaterialNodeSetInputNByKey(blend_mat, Rpr.MaterialInput.COLOR0,IntPtr.Zero));

            //attach blend to object
            Rpr.Check((int)Rpr.ShapeSetMaterial(RenderObjects[1].ObjIntptr, blend_mat));`

@RichardGe

**Comment by bsavery** [comment]
Can you add a more omplete code example?  Just in the interest of time.

**Comment by Mentalarray** [comment]
Yes here if you past this into the main of the Tutorial called 10_light_point it shows error where the material is not removing from the Blend

`int main()
{
	//	enable Radeon ProRender API trace
	//	set this before any rpr API calls
	//	rprContextSetParameterByKey1u(0,RPR_CONTEXT_TRACING_ENABLED,1);

	std::cout << "Radeon ProRender SDK simple rendering tutorial.\n";
	// Indicates whether the last operation has suceeded or not
	rpr_int status = RPR_SUCCESS;
	// Create OpenCL context using a single GPU 
	rpr_context context = NULL;

	// Register Tahoe ray tracing plugin.
	rpr_int tahoePluginID = rprRegisterPlugin(RPR_PLUGIN_FILE_NAME); 
	CHECK_NE(tahoePluginID , -1)
	rpr_int plugins[] = { tahoePluginID };
	size_t pluginCount = sizeof(plugins) / sizeof(plugins[0]);

	// Create context using a single GPU 
	CHECK( rprCreateContext(RPR_API_VERSION, plugins, pluginCount, g_ContextCreationFlags, NULL, NULL, &context) );

	// Set active plugin.
	CHECK(  rprContextSetActivePlugin(context, plugins[0]) );


	rpr_material_system matsys;
	CHECK( rprContextCreateMaterialSystem(context, 0, &matsys) );
	// Check if it is created successfully
	if (status != RPR_SUCCESS)
	{
		std::cout << "Context creation failed: check your OpenCL runtime and driver versions.\n";
		return -1;
	}

	std::cout << "Context successfully created.\n";

	// Create a scene
	rpr_scene scene=nullptr;
	CHECK( rprContextCreateScene(context, &scene) );

	// Create cube mesh
	rpr_shape cube=nullptr;
	{
		CHECK( rprContextCreateMesh(context,
			(rpr_float const*)&cube_data[0], 24, sizeof(vertex),
			(rpr_float const*)((char*)&cube_data[0] + sizeof(rpr_float)*3), 24, sizeof(vertex),
			(rpr_float const*)((char*)&cube_data[0] + sizeof(rpr_float)*6), 24, sizeof(vertex),
			(rpr_int const*)indices, sizeof(rpr_int),
			(rpr_int const*)indices, sizeof(rpr_int),
			(rpr_int const*)indices, sizeof(rpr_int),
			num_face_vertices, 12, &cube) );

		// Add cube into the scene
		CHECK( rprSceneAttachShape(scene, cube) );

		// Create a transform: -2 unit along X axis and 1 unit up Y axis
		RadeonProRender::matrix m = RadeonProRender::translation(RadeonProRender::float3(-2, 1, 0));

		// Set the transform 
		CHECK( rprShapeSetTransform(cube, RPR_TRUE, &m.m00) );
	}
	// Create plane mesh
	rpr_shape plane=nullptr;
	{
		CHECK( rprContextCreateMesh(context,
			(rpr_float const*)&plane_data[0], 4, sizeof(vertex),
			(rpr_float const*)((char*)&plane_data[0] + sizeof(rpr_float)*3), 4, sizeof(vertex),
			(rpr_float const*)((char*)&plane_data[0] + sizeof(rpr_float)*6), 4, sizeof(vertex),
			(rpr_int const*)indices, sizeof(rpr_int),
			(rpr_int const*)indices, sizeof(rpr_int),
			(rpr_int const*)indices, sizeof(rpr_int),
			num_face_vertices, 2, &plane) );

		// Add plane into the scene
		CHECK( rprSceneAttachShape(scene, plane) );
	}
	rpr_shape instance=nullptr;
	{
		rprContextCreateInstance( context, cube, &instance );

		// Create a transform: -2 unit along X axis and 1 unit up Y axis
		RadeonProRender::matrix m = RadeonProRender::translation(RadeonProRender::float3(2, 1, 0));

		// Set the transform 
		CHECK( rprShapeSetTransform(instance, RPR_TRUE, &m.m00) );

		CHECK( rprSceneAttachShape(scene, instance) );
	}
	// Create camera
	rpr_camera camera=nullptr;
	{
		CHECK( rprContextCreateCamera(context, &camera) );

		// Position camera in world space: 
		// Camera position is (5,5,20)
		// Camera aimed at (0,0,0)
		// Camera up vector is (0,1,0)
		CHECK( rprCameraLookAt(camera, 0, 5, 20, 0, 1, 0, 0, 1, 0) );

		CHECK( rprCameraSetFocalLength(camera, 75.f) );

		// Set camera for the scene
		CHECK( rprSceneSetCamera(scene, camera) );
	}
	// Set scene to render for the context
	CHECK( rprContextSetScene(context, scene) );

	// Create simple diffuse shader
	rpr_material_node diffuse=nullptr;
	{
		CHECK( rprMaterialSystemCreateNode(matsys, RPR_MATERIAL_NODE_DIFFUSE, &diffuse) );
		
		// Set diffuse color parameter to gray
		CHECK( rprMaterialNodeSetInputFByKey(diffuse, RPR_MATERIAL_INPUT_COLOR, 0.5f, 0.2f, 0.2f, 1.f) );

		CHECK( rprShapeSetMaterial(plane, diffuse) );
	}
	// Create simple diffuse shader
	rpr_material_node blend_mat = nullptr;
	{
		CHECK( rprMaterialSystemCreateNode(matsys, RPR_MATERIAL_NODE_BLEND, &blend_mat) );	
		// Set Weight parameter to zero
		CHECK( rprMaterialNodeSetInputFByKey(blend_mat, RPR_MATERIAL_INPUT_WEIGHT, 0, 0, 0, 0) );
		CHECK( rprMaterialNodeSetInputNByKey(blend_mat, RPR_MATERIAL_INPUT_COLOR0, diffuse) );

		// Set shader for cube & plane meshes
		CHECK( rprShapeSetMaterial(cube, blend_mat) );

	}

	//now remove the diffuse mat from the blend input COLOR0
	//this line is not working the object still shows the red material
	CHECK( rprMaterialNodeSetInputNByKey(blend_mat, RPR_MATERIAL_INPUT_COLOR0, NULL) );



	// Create framebuffer to store rendering result
	rpr_framebuffer_desc desc = { 800,600 };

	// 4 component 32-bit float value each
	rpr_framebuffer_format fmt = {4, RPR_COMPONENT_TYPE_FLOAT32};
	rpr_framebuffer frame_buffer = nullptr;
	rpr_framebuffer frame_buffer_resolved = nullptr;
	CHECK( rprContextCreateFrameBuffer(context, fmt, &desc, &frame_buffer) );
	CHECK( rprContextCreateFrameBuffer(context, fmt, &desc, &frame_buffer_resolved) );

	// Clear framebuffer to black color
	CHECK( rprFrameBufferClear(frame_buffer) );

	// Set framebuffer for the context
	CHECK( rprContextSetAOV(context, RPR_AOV_COLOR, frame_buffer) );

	///////// Tutorial Create Light //////////

	// Create point light
	rpr_light light=nullptr;
	{
		CHECK(rprContextCreatePointLight(context, &light));

		// Create a transform: move 5 units in X axis, 8 units up Y axis, -2 units in Z axis
		RadeonProRender::matrix lightm = RadeonProRender::translation(RadeonProRender::float3(0, 8, 2));

		// Set transform for the light
		CHECK(rprLightSetTransform(light, RPR_TRUE, &lightm.m00));

		// Set light radiant power in Watts
		CHECK(rprPointLightSetRadiantPower3f(light, 255, 241, 224));

		// Attach the light to the scene
		CHECK(rprSceneAttachLight(scene, light));
	}

	// Progressively render an image
	CHECK(rprContextSetParameterByKey1u(context,RPR_CONTEXT_ITERATIONS,NUM_ITERATIONS));
	CHECK( rprContextRender(context) );
	CHECK(rprContextResolveFrameBuffer(context,frame_buffer,frame_buffer_resolved,true));

	std::cout << "Rendering finished.\n";

	// Save the result to file
	CHECK( rprFrameBufferSaveToFile(frame_buffer_resolved, "10.png") );

	// Release the stuff we created
	CHECK(rprObjectDelete(matsys));matsys=nullptr;
	CHECK(rprObjectDelete(plane));plane=nullptr;
	CHECK(rprObjectDelete(cube));cube=nullptr;
	CHECK(rprObjectDelete(instance));instance=nullptr;
	CHECK(rprObjectDelete(light));light=nullptr;
	CHECK(rprObjectDelete(diffuse));diffuse=nullptr;
	CHECK(rprObjectDelete(blend_mat));blend_mat = nullptr;
	CHECK(rprObjectDelete(scene));scene=nullptr;
	CHECK(rprObjectDelete(camera));camera=nullptr;
	CHECK(rprObjectDelete(frame_buffer));frame_buffer=nullptr;
	CHECK(rprObjectDelete(frame_buffer_resolved));frame_buffer_resolved=nullptr;
	CheckNoLeak(context);
	CHECK(rprObjectDelete(context));context=nullptr; // Always delete the RPR Context in last.
	return 0;
}`

**Comment by RichardGe** [comment]
Hi, you are right. A fix is ready for next release 2.02.2 making sure that  `rprMaterialNodeSetInputNByKey(...  ,  nullptr)` actually removes the material.

**Comment by Mentalarray** [comment]
Many thanks cant wait to test it out
