### ISSUE TITLE
Camera differences in full spectrum rendering

### ISSUE THREAD

**Issue by jrz371** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#18]
Hi,

I've noticed the camera behaves differently in full spectrum rendering versus the ultra rendering modes. The camera setup follows the same code paths on my end but I get vastly different rendering results. The image seems horizontally stretched. Is this a known issue or do I need to setup the cameras differently between the two modes?

![Hybrid](https://user-images.githubusercontent.com/16514346/105363034-460fd780-5c04-11eb-85e7-5cc65fed89a2.PNG)
![Ultra](https://user-images.githubusercontent.com/16514346/105363038-47d99b00-5c04-11eb-8331-a8c665999f55.PNG)

**Comment by bsavery** [comment]
off the top of my head I know we don't support the camera shift for hybrid.  Do you have a simple code snippet for what you're doing in the camera export?

**Comment by jrz371** [comment]
Sure! Here's our camera setup.

`
Rpr.Check(Rpr.CameraSetFocalLength(camera, (float)viewInfo.Viewport.Camera35mmLensLength));

Rpr.Check(Rpr.CameraLookAt(camera, (float)position.X, (float)position.Y, (float)position.Z,
                                     (float)target.X, (float)target.Y, (float)target.Z,
                                     (float)up.X, (float)up.Y, (float)up.Z));

Rpr.Check(Rpr.CameraSetNearPlane(camera, (float)near));

Rpr.Check(Rpr.CameraSetFarPlane(camera, (float)far));
`

**Comment by RichardGe** [comment]
Hi @jrz371 , are you using  rprCameraSetSensorSize ?  I advise you to update it each time the framebuffer size changes, it helps both plugins to keep the same aspect ratio.

**Comment by jrz371** [comment]
Thanks!

Setting that seems to have resolved it. It is a bit odd though. The frame buffers are the same size each time. It seems like the hybrid render either has different defaults, or calculate it differently when not explicitly set.

**Comment by bsavery** [comment]
Maybe the default should be set the same for hybrid and RPR @RichardGe
