### ISSUE TITLE
OpenGL interop issues with hybrid backend

### ISSUE THREAD

**Issue by Flamaros** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#19]
I am now able to create the context with the hybrid backend with my GPU that have less than 4GB of VRAM.
I made some other fixes in my code, but I can't figure out what I do incorrectly to retrieve the result of the render() call in my OpenGL texture.

I am creating the context with RPR_CREATION_FLAGS_ENABLE_GL_INTEROP | RPR_CREATION_FLAGS_ENABLE_DEBUG | RPR_CREATION_FLAGS_ENABLE_GPU0 as flags.

I am creating the FBO by calling rprContextCreateFramebufferFromGLTexture2D(g_context, GL_TEXTURE_2D, 0, g_texture, &g_frame_buffer);

The in my draw function, I am calling the rprContextRender function before using the g_texture that I draw on the viewport sized quad.

I am getting following Vulkan errors:
Error: Can't wait until fence is signalled, VkResult=-4
Error: Failed to submit to a queue, VkResult=-4

I also noticed that if I create the OpenGL context with version 3.2 instead of 3.0, my test application doesn't render anything with the path-tracer backend.

Is it easier to make both backends (hybrid and Northstar64) working with Vulkan?

**Comment by Flamaros** [comment]
I just tested with the latest version v2.2.0, I still have the same issue.

**Comment by Flamaros** [comment]
I just check if I have the same issue with the tutorial 63_hybrid, sadly it is the casse.

Here is the full log:
```Radeon ProRender SDK matball scene rendering tutorial.
Error: Required device extension VK_KHR_shader_atomic_int64 is not supported.
Program "compute_ibl_brdf_lut.comp" compilation time: 153 ms
Context successfully created.
Unsupported node type: PostEffect
Unsupported node type: PostEffect
Program "apply_gamma.comp" compilation time: 4 ms
Rendering scene ... Program "frustum_culling.comp" compilation time: 13 ms
Program "clear_counter.comp" compilation time: 1 ms
Program "spheremap_project_to_sh9.comp" compilation time: 7 ms
Program "calc_ibl_cdf.comp" compilation time: 16 ms
Program "compute_ibl_reflections.comp" compilation time: 31 ms
Program "tiles_generate_frustums.comp" compilation time: 10 ms
Program "sh9_reduce.comp" compilation time: 13 ms
Program "calculate_ibl_luminance.comp" compilation time: 5 ms
Program "calculate_cdf.comp" compilation time: 1 ms
Program "advance_counter.comp" compilation time: 0 ms
Program "reflections_denoise_spatial.comp" compilation time: 23 ms
Program "reflections_denoise_temporal.comp" compilation time: 9 ms
Program "reflections_denoise_eaw.comp" compilation time: 6 ms
Program "reflections_modulate_brdf.comp" compilation time: 1 ms
Program "fullscreen_quad.vert" compilation time: 0 ms
Program "taa.frag" compilation time: 9 ms
Program "taa_copy_to_history.comp" compilation time: 1 ms
Program "tiles_cull_lights.comp" compilation time: 7 ms
Program "visibility_buffer.vert" compilation time: 7 ms
Program "visibility_buffer.frag" compilation time: 15 ms
Program "generate_barycentrics.comp" compilation time: 8 ms
Program "frustum_culling.comp" compilation time: 11 ms
Program "copy_depth.comp" compilation time: 1 ms
Program "downsample_z_buffer.comp" compilation time: 1 ms
Program "calc_ssao.comp" compilation time: 7 ms
Program "bilateral_filter.comp" compilation time: 3 ms
Program "fullscreen_quad.vert" compilation time: 0 ms
Program "raster_shade.frag" compilation time: 38 ms
Program "screenspace_reflections_intersect.comp" compilation time: 19 ms
Program "screenspace_reflections_resolve.comp" compilation time: 20 ms
Program "raster_combine.comp" compilation time: 4 ms
Program "weighted_oit.frag" compilation time: 40 ms
Program "raster_combine_transparency.comp" compilation time: 5 ms
Program "fullscreen_quad_configurable_uv.vert" compilation time: 1 ms
Program "copy_image.frag" compilation time: 1 ms
finished.
Error: Can't wait until fence is signalled, VkResult=-4
Error: Failed to submit to a queue, VkResult=-4
ERROR detected - program will stop.
file = C:\Users\Xavier\Documents\development\arch-crafter\third-party\RadeonProRenderSDK\tutorials\63_hybrid\main.cpp
line = 222
error code = -18
Assertion failed: 0, file C:\Users\Xavier\Documents\development\arch-crafter\third-party\RadeonProRenderSDK\tutorials\common\common.h, line 134```

I modified the code a little bit to fix the context creation as my GPU doesn't have enough memory.
The line 222 is the following:

```CHECK(rprFrameBufferSaveToFile(frame_buffer, "63.png"));```

**Comment by Flamaros** [comment]
I have the same issue with both of my GPUs installed onmy laptop, one of them have the VK_KHR_shader_atomic_int64 extension.

**Comment by Flamaros** [comment]
After some testing on a desktop computer, I think that a part my issue come from drivers. My desktop computer have a 980GTX and I was able to run the 63_hybrid tutorial correctly on it.

But the 63_hybrid tutorial doesn't use GL_Interop. With my test application even on my desktop the RPR_CREATION_FLAGS_ENABLE_GL_INTEROP doesn't seems to work correctly, I have no error, but also no rendering.

When I check with Nividia nisght I have a warning telling that my texture attached to the frame_buffer may contains undefined data.

Need I do something particular with the texture before or after the call of rprContextRender?


I am creating the texture like this just before the framebuffer creation:
```		glGenTextures(1, &g_texture);

		glBindTexture(GL_TEXTURE_2D, g_texture);
		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);

                glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA32F, width, height, 0, GL_RGBA, GL_FLOAT, NULL);
		glBindTexture(GL_TEXTURE_2D, 0);

		CHECK(rprContextCreateFramebufferFromGLTexture2D(g_context, GL_TEXTURE_2D, 0, g_texture, &g_frame_buffer));
			
		// Set framebuffer for the context
		CHECK(rprContextSetAOV(g_context, RPR_AOV_COLOR, g_frame_buffer));
```

**Comment by RichardGe** [comment]
This is related to issues/20 , as I said in this ticket, I need to come up with a Demo for Hybrid+OpenGL in the tutorial.
That should help
