### ISSUE TITLE
Hybrid Mode Fails

### ISSUE THREAD

**Issue by danelss** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#2]
We are unable to use the Hybrid mode in the latest AMD Radeon Pro SDK (downloaded from Github, RadeonProRenderSDK-1.35.2.zip). 

Compiling and running the “tutorials/63_hybrid” tutorial fails to create the context and we got the output attached (Log.txt). It seems to be some Vulkan issue (I assume that the Hybrid.dll is actually using Vulkan as a backend).
What we tried:

1. Various combinations of RPR_CREATION_FLAGS_ENABLE_GPU0- RPR_CREATION_FLAGS_ENABLE_GPU
2. Enable debug logging by specifying RPR_CREATION_FLAGS_ENABLE_DEBUG to no avail (the Tahoe64.dll plugin is logging stuff into tahoe.log, the Hybrid.dll seems to ignore this flag).

[Report.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK/files/4826444/Report.zip)

**Comment by RichardGe** [comment]
@danelss 
Could you please tell us your  GPU, driver, OS ?

**Comment by danelss** [comment]
Hi @RichardGe,
All the info is inside the SystemReport in the .zip file.

Microsoft Windows 10 Enterprise (x64) Build 17763.1282 (1809/RS5) 
NVIDIA GeForce GTX 1050 Ti (GP107M) 
26.21.14.4587 (GeForce 445.87) 

This also happened in another machine running  Ubuntu 20.04 with an AMD R9 380.

**Comment by bsavery** [comment]
Hi @danelss 
Couple things here. Hybrid requires > 4gb memory by default.  But you can actually edit this!  (Sorry this could be documented better).  

When you make the Context you can control this with context properties:
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK/blob/4321456f0684286e102dc84a8fa3498b60a5ee6c/RadeonProRender/inc/RadeonProRender_Baikal.h#L30-L34

The default sizes are:
#define RPR_CONTEXT_CREATEPROP_HYBRID_ACC_MEMORY_SIZE 0x1601.      - 1gb
#define RPR_CONTEXT_CREATEPROP_HYBRID_VERTEX_MEMORY_SIZE 0x1602.     - 1.5Mb
#define RPR_CONTEXT_CREATEPROP_HYBRID_INDEX_MEMORY_SIZE 0x1603.       - 128mb
#define RPR_CONTEXT_CREATEPROP_HYBRID_STAGING_MEMORY_SIZE.   - 512mb

So if you set those to something smaller it should work on cards with less memory.

**Comment by bsavery** [comment]
@danelss did that help?

**Comment by danelss** [comment]
Hello, I forwarded it to my team and am waiting to hear from them, but from the last things I heard they got it working.
I will confirm and close the issue next week, thanks!

**Comment by danelss** [comment]
Thank you, it's working now!
