### ISSUE TITLE
Displacement map visualization gets clipped within the bounds of some geometries

### ISSUE THREAD

**Issue by synthetica3d** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#28]
![displ_bug](https://user-images.githubusercontent.com/64734773/118569779-f4e0b080-b7bd-11eb-925c-78527a5bcc09.png)

In this image, you can see a displacement map on a plane. The displacement in this case gets clipped within the boundaries of the plane geometry. I have seen more similar clipping artefacts with other geometries as well.

**Comment by synthetica3d** [comment]
Forgot the mention, engine is NorthStar

**Comment by bsavery** [comment]
Can you attach some way to repro this?

**Comment by synthetica3d** [comment]
[trace.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK/files/6527887/trace.zip)

I have attached a trace. In addition, there doesn't seem to be a way of applying UV repeat factor to a displacement texture? The displacement texture object is attached directly to the mesh. The other textures are assigned an arithmetic node multiplying a input UV lookup node, to achieve texture scale (repeat factor). How can we achieve the same for displacement?

**Comment by synthetica3d** [comment]
Technically, I believe the engine is still using the original bounding box of the mesh to perform clipping and culling. The bounding box should be expanded accordingly to the displacement.

**Comment by synthetica3d** [comment]
![screenshot_0152](https://user-images.githubusercontent.com/64734773/123182545-09a61780-d4d3-11eb-814a-e67ac2cd8489.png)

The problem has been fixed. Good job!
