### ISSUE TITLE
Support for clipping planes

### ISSUE THREAD

**Issue by jrz371** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#29]
Is there a possibility for supporting clipping planes in ProRender? Or a way to recreate the feature with the current version of the SDK? I've had a few feature requests come in for this and it would be nice to support.

An example of Rhinos clipping planes
![Clipping Planes](https://user-images.githubusercontent.com/16514346/120316851-8c79ef00-c2e6-11eb-98b1-02b0f0531757.gif)

**Comment by RichardGe** [comment]
it's now implemented - check the demo:
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK/tree/master/tutorials/27_cutplanes

**Comment by jrz371** [comment]
Works great, thanks!
