### ISSUE TITLE
Add example for using the RPR_CONTEXT_COMPILE_CALLBACK_FUNC

### ISSUE THREAD

**Issue by jrz371** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#33]
I'm assuming this is the callback function for when compiling the kernels. It'd be nice to have an example so I can use it as well to provide clearer output messages to the user when renders begin.

**Comment by bsavery** [comment]
@takahiroharada does this work in Northstar?

**Comment by RichardGe** [comment]
this callback is no longer supported inside Northstar.
