### ISSUE TITLE
Provisional ANARI 1.0 API support?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#37]
Hi,
seems spec 1.0 API has been released:
and an AMD implementation seems coming soon:
"We look forward to supporting multiple platforms for GPU and CPU rendering via our Radeon ProRender backend for ANARI, which is expected to be available soon at GPUOpen.com" from:
"https://www.khronos.org/news/press/khronos-announces-public-release-of-the-anari-1.0-provisional-specification"
so just opening issue to get notified when is posted.. :-)

**Comment by bsavery** [comment]
Will update you, it's coming soon.  We had been working with the provisional spec, and are updating now, it will be on GPUOpen here as a GitHub repo.

**Comment by oscarbg** [comment]
any update? 
no pressure but seems both Intel and Nvidia have released some beta releases..

**Comment by bsavery** [comment]
Good timing.  We're just finishing up the business side of open sourcing things and are hoping to have it out this month.  (The development is done) 

If you're in a hurry please send me an email Brian (dot) Savery (at) AMD.com for more info.

**Comment by oscarbg** [comment]
thanks for the update! good news.. I can wait for public release this month!

**Comment by bsavery** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderANARI Here!
