### ISSUE TITLE
API transition guide not accessible

### ISSUE THREAD

**Issue by BearishSun** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#4]
Release notes reference the following link: https://github.com/Radeon-Pro/RadeonProRenderSDK/wiki/1.34.9-1.35.0-transition-for-RPR-developers

But it cannot be accessed (Nor can the Wiki page be opened at all).

**Comment by RichardGe** [comment]
This link is an old repo that we have closed now.

The main change was about env light override.

remove of :
rprSceneSetEnvironmentOverride 
rprSceneGetEnvironmentOverride 
rprEnvironmentLightSetEnvironmentOverride
rprEnvironmentLightGetEnvironmentOverride

replaced by :   
rprEnvironmentLightSetEnvironmentLightOverride
rprEnvironmentLightGetEnvironmentLightOverride

You can override different types of lights :  
RPR_ENVIRONMENT_LIGHT_OVERRIDE_REFLECTION
RPR_ENVIRONMENT_LIGHT_OVERRIDE_REFRACTION
RPR_ENVIRONMENT_LIGHT_OVERRIDE_TRANSPARENCY
RPR_ENVIRONMENT_LIGHT_OVERRIDE_BACKGROUND


Example: 
rprSceneAttachLight(scene, iblA);
rprEnvironmentLightSetEnvironmentLightOverride(iblA, RPR_ENVIRONMENT_LIGHT_OVERRIDE_REFLECTION, iblB);
Means the scene is going to use iblA for the lighting.  Except for the "reflection" lighting : iblB will be used. 

I think that was the only difference between 34.9 and 35.0. But if you have other questions about this transition, feel free to ask.
