### ISSUE TITLE
rprContextCreateSkyLight fails with error code -12 RPR_ERROR_INVALID_PARAMETER

### ISSUE THREAD

**Issue by matlemuzic** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#43]
Hi there,

I am trying to create a sky light in a program based on 63_hybrid, and I get an error code -12 when calling rprContextCreateSkyLight(context, &light));

Thanks in advance.

**Comment by RichardGe** [comment]
Sky Light is no longer supported. 
I suggest to use rprContextCreateEnvironmentLight instead.
