### ISSUE TITLE
Prorender for Maya 2023

### ISSUE THREAD

**Issue by yucelyilmazvfx** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#53]
I can't install Pro Render to Maya 2023. Supports up to 2022. Please add support for 2023 too. Thanks

**Comment by RichardGe** [comment]
support for Maya has been added in 3.4.0
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin/releases/tag/v3.4.0
