### ISSUE TITLE
Assigned material on mesh only rendering properly some of the time. 

### ISSUE THREAD

**Issue by nativetazuma** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#55]
I'm having trouble with assigned materials to part of a mesh only rendering sometimes, the render seems to only work a small percentage of the time. I tried to render the part of the mesh using the glass material in proRender and principled BSDF with the same issues.

The hair is another story, I may have to modify the color sliders to get that to render properly or replace it entirely. I'm using hair cards from curve to mesh, and put a color slider on top to control the color fade.

Setup: 
Blender 3.3 with GPU compute 
processor: AMD Ryzen 7 3700X 8-Core Processor  3.60 GHz
OS: Windows 11 home 22H2 build 22621.674
GPU: AMD Radeon RX 6700 XT
AMD software: Adrenalin Edition version 22.Q2
installed memory: 48GB 
BaseBoard Product:	MPG X570 GAMING EDGE WIFI (MS-7C37)

![knee disc not rendering ](https://user-images.githubusercontent.com/55822152/197235695-4d292b5f-aa95-4a2b-a5f9-c8e2a42df5c2.png)
![eyes not rendering properly ](https://user-images.githubusercontent.com/55822152/197235701-38eec875-10f5-49b5-82d6-4a51c6c2b557.png)

Intended render 

![intended render disc](https://user-images.githubusercontent.com/55822152/197235742-9d32a5e5-3dbf-4668-a83f-70e88c147677.png)
![intended render eyes](https://user-images.githubusercontent.com/55822152/197235747-66728c30-ddb1-47fa-9673-e7a263e9bdee.png)

**Comment by bsavery** [comment]
can you post this on https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon

**Comment by RichardGe** [comment]
Closing this issue as it's not directly related to the RPR SDK but to RPR Blender plugins.

Just for information, 
From the RPR SDK point of view, in order to assign material to part of mesh only, we can use the per-face material which is illustrated in this demo:
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK/tree/master/tutorials/34_material_per_face
