### ISSUE TITLE
Hybrid and Northstar64 mode not working

### ISSUE THREAD

**Issue by WannaBeKratos** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#56]
![image](https://user-images.githubusercontent.com/77170000/202929893-659c30c1-e912-4392-9968-1fd5c31a119d.png)
Machine:
Win 11
cpu: Amd Ryzen 5 2600 Six-core
gpu: Nvidia 1070 Ti ( Drivers 517.83) 
I also tried with the latest drivers

**Comment by bsavery** [comment]
Hi there.  There is an issue with latest Nvidia drivers (they broke something).  We recommend 516.94

**Comment by WannaBeKratos** [comment]
Hi, thanks for replaying, I have tried with the driver you suggested and even with an older driver, I still get the same error, I get the same error with previous version of pro renderer as well, any other driver that may be the issue ?

**Comment by WannaBeKratos** [comment]
I have also tried under WSL but no luck.

**Comment by WannaBeKratos** [comment]
It turns out that the error I was getting was pretty descriptive, I was accessing invalid memory while porting a few of the examples to rust. Now both plugins seams to work perfectly fine even on the latest Nvidia drivers. I'm closing this issue as I found a way to solve it.
