### ISSUE TITLE
Prorender 3.4 and 3.3 crashes Blender 

### ISSUE THREAD

**Issue by Snoiteandthesv3ndwarves** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#58]
When disabling, removing, loading factory settings, or Quit, Blender 3.3 and 3.4 crash.

**Comment by bsavery** [comment]
Please file this issue here:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues
