### ISSUE TITLE
Depth AOV generate empty image

### ISSUE THREAD

**Issue by marceloroca** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#6]
Wen generate RPR_AOV_DEPTH the result image is empty.

I'm using the tutorial 33_aov, with this changes:

// before render
	rpr_framebuffer frame_buffer_depth, frame_buffer_depth2;
	CHECK(rprContextCreateFrameBuffer(context, fmt, &desc, &frame_buffer_depth));
	CHECK(rprContextCreateFrameBuffer(context, fmt, &desc, &frame_buffer_depth2));
	CHECK(rprFrameBufferClear(frame_buffer_depth));
	CHECK(rprFrameBufferClear(frame_buffer_depth2));
	CHECK(rprContextSetAOV(context, RPR_AOV_DEPTH, frame_buffer_depth));

// after render
	CHECK(rprContextResolveFrameBuffer(context, frame_buffer_depth, frame_buffer_depth2, true));
	CHECK(rprFrameBufferSaveToFile(frame_buffer_depth2, "33_depth.png"));

OS: Windows 10
GPU: Radeon RX 5500 XT
Driver: 20.5.1

![33_depth](https://user-images.githubusercontent.com/153597/88069472-800dfd00-cb3f-11ea-86a5-7daa5d897446.png)

**Comment by bsavery** [comment]
Are you looking at the image in an editor?  Keep in mind the Z values might not be normalized to 0-1

**Comment by marceloroca** [comment]
Yes I'm looking image with photoshop. But If I use the generated depth image with RPR_AOV_DEPTH with the RIF_IMAGE_FILTER_DEPTH_OF_FIELD filter, the depth of field effect is not applied.

[DOF.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK/files/4955854/DOF.zip)

**Comment by marceloroca** [comment]
I check the image min and max values with FrameBufferGetInfo RPR_FRAMEBUFFER_DATA and the values are:

min: 1
max: 10000

Maybe the problem is with RadeonImageFilters

**Comment by marceloroca** [comment]
thank you, was solved in https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/issues
