### ISSUE TITLE
Getting RGB values from frame buffer 

### ISSUE THREAD

**Issue by WannaBeKratos** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#67]
Is there a way to get RGBA values from frame buffer ? The closes' thing I found to it is under the ocio tutorial. Any further insight for me ?
Another question, how is a preview in software like Blender and Maya achieved, am I supposed to use one of the interop headers like RadeonProRender_VK ?

**Comment by bsavery** [comment]
You can cast a resolved framebuffer to a float array.  Or rprFrameBufferSaveToFile.

Blender works basically by casting the framebuffer to a float array and then copying up to OpenGL

**Comment by WannaBeKratos** [comment]
One more question.  The values returned (float array) are not actual pixel values, those are stored somewhere also, correct ? I am getting some values from the framebuffer, but when I save the data as an image, I get a different image from rprFrameBufferSaveToFile.

**Comment by WannaBeKratos** [comment]
I manage to solve the issue, I had to do a little conversion of the frame buffer. Closing
