### ISSUE TITLE
RPR_CONTEXT_Y_FLIP not working

### ISSUE THREAD

**Issue by marceloroca** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#8]
// do nothing
CHECK(rprContextSetParameterByKey1u(context, RPR_CONTEXT_Y_FLIP, 1u));

// flip horizontally correctly
CHECK(rprContextSetParameterByKey1u(context, RPR_CONTEXT_X_FLIP, 1u));

**Comment by RichardGe** [comment]
could you specify the plugin that you are using ?  
Tahoe / Hybrid / Northstar ?

**Comment by marceloroca** [comment]
Tahoe and Northstar

**Comment by RichardGe** [comment]
This is because 1 is the default. If you set 0, it will flipY the image.
In other words, by default, image is always flipped on Y.
